service: serverless-practice
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-api-gateway-throttling

custom:
  apiGatewayThrottling:
    maxRequestPerSecond: 10
    maxConcurrentRequests: 5

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  costNotifier:
    handler: src/costNotifier.handler
    events:
      # 日本時間で毎朝9時
      - schedule: cron(0 0 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URL}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ce.GetCostAndUsage
        Resource: '*'

  myHello:
    handler: src/myHello.handler
    events:
      - httpApi:
          method: get
          path: /hello
